from fpdf import FPDF
import os

class ReportService:
    @staticmethod
    def generate_pdf(category: str, data: dict, output_path: str):
        pdf = FPDF()
        pdf.add_page()
        
        # 1. Header with styling
        pdf.set_fill_color(26, 43, 60) # Deep Navy
        pdf.rect(0, 0, 210, 40, 'F')
        
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 24)
        pdf.set_y(15)
        pdf.cell(0, 10, f"CROSS-BORDER INTEL REPORT", ln=True, align="C")
        pdf.set_font("Helvetica", "", 12)
        pdf.cell(0, 10, f"Category Analysis: {category.upper()}", ln=True, align="C")
        
        pdf.ln(20)
        pdf.set_text_color(0, 0, 0)
        
        # 2. Market Compass Section
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(26, 43, 60)
        pdf.cell(0, 10, "1. Global Market Compass", ln=True)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)
        
        recs = data.get("recommendations", {})
        for key, value in recs.items():
            pdf.set_font("Helvetica", "B", 12)
            color = (39, 174, 96) if "profit" in key else (41, 128, 185) if "mass" in key else (142, 68, 173)
            pdf.set_text_color(*color)
            pdf.cell(0, 8, f"[{key.replace('_', ' ').upper()}]", ln=True)
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Helvetica", "", 10)
            for country in value:
                pdf.cell(0, 6, f"  > {country['name']}: GDP Per Capita ${country['gdp_per_capita']}, Growth {country['growth']}%", ln=True)
            pdf.ln(3)

        # 3. Local E-commerce Trends (New Section)
        pdf.ln(5)
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(26, 43, 60)
        pdf.cell(0, 10, "2. Regional E-commerce Insights", ln=True)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)
        
        ecom_data = data.get("ecom_trends", {})
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(0, 0, 0)
        for region, items in ecom_data.items():
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 8, f"Region: {region}", ln=True)
            pdf.set_font("Helvetica", "", 10)
            for item in items:
                pdf.cell(0, 6, f"  * {item['product']} on {item['platform']} (Trend: {item['trend']} | Growth: {item['growth']})", ln=True)
            pdf.ln(2)

        # 4. AI Strategic Insight
        pdf.ln(5)
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(26, 43, 60)
        pdf.cell(0, 10, "3. AI Strategic Summary", ln=True)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)
        
        pdf.set_font("Helvetica", "I", 11)
        pdf.set_text_color(50, 50, 50)
        pdf.multi_cell(0, 7, data.get("ai_insight", ""))
        
        # 5. Footer
        pdf.set_y(-20)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "Confidential - Generated by Accio Cross-border Intel App", ln=False, align="L")
        pdf.cell(0, 10, "Page 1 of 1", ln=False, align="R")
        
        # Ensure directory exists
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        pdf.output(output_path)
        return output_path
