from fpdf import FPDF
import os

class ReportService:
    @staticmethod
    def generate_pdf(category: str, data: dict, output_path: str):
        pdf = FPDF()
        pdf.add_page()
        
        # Add font that supports Chinese or use standard Latin for now
        # Note: fpdf2 supports TTF fonts for Chinese. For this MVP, we use English labels.
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, f"Cross-border Export Intelligence Report: {category}", ln=True, align="C")
        pdf.ln(10)
        
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 10, "1. Market Recommendations", ln=True)
        pdf.set_font("Helvetica", "", 10)
        
        recs = data.get("recommendations", {})
        for key, value in recs.items():
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 8, f"- {key.replace('_', ' ').title()}:", ln=True)
            pdf.set_font("Helvetica", "", 10)
            for country in value:
                pdf.cell(0, 6, f"  * {country['name']} (GDP: ${country['gdp_per_capita']}, Growth: {country['growth']}%)", ln=True)
        
        pdf.ln(10)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 10, "2. AI Sourcing Insights", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, data.get("ai_insight", "Focus on high-quality and fast-charging features."))
        
        pdf.ln(10)
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 10, "Generated by Accio Cross-border Intelligence App - 2026", ln=True, align="R")
        
        # Ensure directory exists
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        pdf.output(output_path)
        return output_path
