from fpdf import FPDF
import os
from datetime import datetime

class PDF(FPDF):
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()} | Cross-border Intel Report - Generated by GlobalAlpha", 0, 0, "C")

class ReportService:
    @staticmethod
    def generate_pdf(category: str, data: dict, output_path: str):
        pdf = PDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        
        # --- COVER PAGE ---
        pdf.add_page()
        # Visual Background
        pdf.set_fill_color(15, 23, 42) # Slate-900
        pdf.rect(0, 0, 210, 297, 'F')
        
        # Accent Stripe
        pdf.set_fill_color(79, 70, 229) # Indigo-600
        pdf.rect(0, 40, 5, 100, 'F')
        
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 40)
        pdf.set_y(80)
        pdf.set_x(20)
        pdf.cell(0, 20, "MARKET", ln=True)
        pdf.cell(0, 20, "INTELLIGENCE", ln=True)
        
        pdf.ln(10)
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_x(20)
        pdf.set_text_color(129, 140, 248) # Indigo-400
        pdf.cell(0, 10, f"{category.upper()}", ln=True)
        
        pdf.set_font("Helvetica", "", 12)
        pdf.set_text_color(148, 163, 184) # Slate-400
        pdf.set_y(250)
        pdf.set_x(20)
        pdf.cell(0, 6, f"Generated for: {data.get('username', 'Enterprise User')}", ln=True)
        pdf.cell(0, 6, f"Date: {datetime.now().strftime('%B %d, %Y')}", ln=True)
        pdf.cell(0, 6, "CONFIDENTIAL | FOR INTERNAL USE ONLY", ln=True)

        # Helper for Section Headers
        def add_section_header(title, icon=""):
            pdf.add_page()
            pdf.set_fill_color(248, 250, 252) # Slate-50
            pdf.rect(0, 0, 210, 40, 'F')
            pdf.set_y(15)
            pdf.set_x(20)
            pdf.set_font("Helvetica", "B", 24)
            pdf.set_text_color(30, 41, 59) # Slate-800
            pdf.cell(0, 10, f"{icon} {title}", ln=True)
            pdf.set_draw_color(79, 70, 229)
            pdf.set_line_width(1)
            pdf.line(20, 32, 190, 32)
            pdf.ln(15)

        # --- SECTION 1: GLOBAL LAYOUT ---
        add_section_header("1. Global Market Layout", "G")
        pdf.set_text_color(51, 65, 85)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 7, f"Based on our proprietary 'Global 80% Compass' algorithm, we have identified the following strategic markets for {category}. Our selection is balanced between immediate profitability and long-term scaling potential.")
        pdf.ln(5)

        recs = data.get("recommendations", {})
        for key, countries in recs.items():
            pdf.set_fill_color(241, 245, 249)
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 10, f"  {key.replace('_', ' ').title()}", ln=True, fill=True)
            pdf.ln(2)
            for country in countries:
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_x(25)
                pdf.cell(40, 7, f"• {country['name']}")
                pdf.set_font("Helvetica", "", 9)
                details = data.get("market_details", {}).get(country['name'], {})
                pdf.cell(0, 7, f"Macro: GDP ${details.get('gdp')} | Pop: {details.get('population')}M", ln=True)
            pdf.ln(5)

        # --- SECTION 2: COMPETITOR MONITORING ---
        add_section_header("2. Pricing & Competitors", "C")
        pricing = data.get("pricing_analysis", {})
        for region, info in pricing.items():
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(79, 70, 229)
            pdf.cell(0, 10, f"REGION: {region}", ln=True)
            pdf.set_text_color(0, 0, 0)
            
            # Draw a table-like structure for pricing
            pdf.set_font("Helvetica", "", 9)
            pdf.set_x(25)
            pdf.cell(40, 6, "Entry-Level:", 0)
            pdf.cell(30, 6, f"{info['currency']} {info['entry_level']}", 1, 1, "C")
            pdf.set_x(25)
            pdf.cell(40, 6, "Mid-Range:", 0)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(30, 6, f"{info['currency']} {info['mid_range']}", 1, 1, "C")
            pdf.set_x(25)
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(40, 6, "Premium Tier:", 0)
            pdf.cell(30, 6, f"{info['currency']} {info['premium']}", 1, 1, "C")
            
            pdf.ln(2)
            pdf.set_x(25)
            pdf.set_font("Helvetica", "I", 9)
            pdf.cell(0, 6, f"Top Products: {', '.join([p['name'] for p in info.get('top_products', [])])}", ln=True)
            pdf.ln(5)

        # --- SECTION 3: TRADE & LOGISTICS ---
        add_section_header("3. Trade & Customs", "T")
        c = data.get("customs_stats", {})
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, f"HS CODE: {c.get('hs_code', 'N/A')}", ln=True)
        pdf.ln(2)
        
        # Tariffs Box
        pdf.set_fill_color(254, 242, 242) # Red-50
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 8, " IMPORT TARIFFS & BARRIERS", ln=True, fill=True)
        pdf.set_font("Helvetica", "", 9)
        for market, tariff in c.get("tariffs", {}).items():
            pdf.set_x(25)
            pdf.cell(40, 6, f"{market}:")
            pdf.cell(0, 6, tariff, ln=True)
        pdf.ln(5)

        # Risk Box
        pdf.set_fill_color(255, 251, 235) # Amber-50
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 8, " COMPLIANCE & RISK ALERTS", ln=True, fill=True)
        pdf.set_font("Helvetica", "", 9)
        for alert in c.get("risk_alerts", []):
            pdf.set_x(25)
            pdf.multi_cell(0, 6, f"! {alert}")
        
        # --- SECTION 4: STRATEGIC INSIGHT ---
        add_section_header("4. Strategic Action Plan", "S")
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 10, "Executive Insight:", ln=True)
        pdf.set_font("Helvetica", "I", 11)
        pdf.set_text_color(30, 41, 59)
        pdf.multi_cell(0, 8, data.get("ai_insight", "Leverage low-tariff RCEP markets for volume while establishing premium branding in US/EU markets via high-spec certifications."))
        
        pdf.ln(10)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 10, "Industry Compliance Strategy:", ln=True)
        for item in data.get("compliance_info", []):
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 8, f"• {item['category']} Path", ln=True)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_x(25)
            pdf.multi_cell(0, 6, item['breakthrough'])
            pdf.ln(2)

        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        pdf.output(output_path)
        return output_path
